### ISSUE TITLE
Execution error of some examples when tracing of msg processes is enabled

### ISSUE THREAD

**Issue by mpoquet** [mquinson/simgrid#15]
Hello,
I'm currently creating a MSG-based simulator. When I enable tracing (with --cfg=tracing:1 --cfg=tracing/msg/process:1) I get an exception saying that a container (corresponding to a process) cannot be found.

As a MWE, I found that the example masterslave_kill.c (examples/msg/masterslave) crashes in the same way. Some steps to reproduce the error are given above.

cd SG_DEV_ROOT
cd examples/msg/masterslave
gcc -g -lsimgrid -o msk masterslave_kill.c
./msk ../../platforms/small_platform.xml deployment_masterslave_kill.xml --cfg=tracing:1 --cfg=tracing/msg/process:1

**Comment by mpoquet** [comment]
The problem seems to be in file msg_process.c at line 174. The crash seems to occur when, in the simcall_process_create call (just above), SIMIX decides to execute the process instantly.

**Comment by schnorr** [comment]
I was able to reproduce the problem here:

$ ./msk  ../../platforms/small_platform.xml deployment_masterslave_kill.xml --cfg=tracing:1 --cfg=tracing/msg/process:1
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'tracing' to '1'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'tracing/msg/process' to '1'
[Tremblay:master:(1) 0.000000] [msg_test/INFO] Hello!
[Fafard:slave:(2) 0.000000] [msg_test/INFO] Hello!
[Fafard:slave:(2) 0.000000] [msg_test/INFO] Suspending myself
** SimGrid: UNCAUGHT EXCEPTION received on ./msk(2): category: tracing error; value: 1
** container with name slave-2 not found
** Thrown by slave() in this process
[Fafard:slave:(2) 0.000000] /home/schnorr/svn/simgrid/src/xbt/ex.c:148: [xbt_ex/CRITICAL] container with name slave-2 not found

**   In PJ_container_get() at /home/schnorr/svn/simgrid/src/instr/instr_paje_containers.c:145
**   In TRACE_msg_process_suspend.part.5() at /home/schnorr/svn/simgrid/src/msg/instr_msg_process.c:91
**   In MSG_process_suspend() at /home/schnorr/svn/simgrid/src/msg/msg_process.c:440
**   In slave() at /home/schnorr/svn/simgrid/examples/msg/masterslave/masterslave_kill.c:21
**   In smx_ctx_raw_stop() at /home/schnorr/svn/simgrid/src/simix/smx_context_raw.c:402
Aborted

The problem disappears when tracing is disabled.

**Comment by mquinson** [comment]
Actually, the patch is breaking the tests. See https://travis-ci.org/mquinson/simgrid/builds/70967183 for example...

I will revert the change for now. I hope that you will provide an updated version in the future.

**Comment by mquinson** [comment]
@mpoquet is there any progress on that problem, maybe? What is the current status anyway?
Thanks,

**Comment by mpoquet** [comment]
The problem still appears on current version (I just tested it with revision b7630a950a6b).
It only appears when tracing is enabled.

I did not progress on this issue. I will inspect it this evening.

#### Output (no tracing)
```
$ ./msk ../../platforms/small_platform.xml deployment_masterslave_kill.xml
[Tremblay:master:(1) 0.000000] [msg_test/INFO] Hello!
[Fafard:slave:(2) 0.000000] [msg_test/INFO] Hello!
[Fafard:slave:(2) 0.000000] [msg_test/INFO] Suspending myself
[Tremblay:master:(1) 10.000000] [msg_test/INFO] Resume process
[Tremblay:master:(1) 10.000000] [msg_test/INFO] Kill process
[Tremblay:master:(1) 10.000000] [msg_test/INFO] OK, goodbye now.
[10.000000] [msg_test/INFO] Simulation time 10
```

#### Output (tracing enabled)

```
$ ./msk ../../platforms/small_platform.xml deployment_masterslave_kill.xml --cfg=tracing:1 --cfg=tracing/msg/process:1
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'tracing' to '1'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'tracing/msg/process' to '1'
[Tremblay:master:(1) 0.000000] [msg_test/INFO] Hello!
[Fafard:slave:(2) 0.000000] [msg_test/INFO] Hello!
[Fafard:slave:(2) 0.000000] [msg_test/INFO] Suspending myself
** SimGrid: UNCAUGHT EXCEPTION received on ./msk(2): category: tracing error; value: 1
** container with name slave-2 not found
** Thrown by slave() in this process
[Fafard:slave:(2) 0.000000] /home/carni/proj/simgrid-martin/src/xbt/ex.c:148: [xbt_ex/CRITICAL] container with name slave-2 not found
/usr/bin/addr2line: Dwarf Error: Info pointer extends beyond end of attributes
/usr/bin/addr2line: Dwarf Error: Info pointer extends beyond end of attributes

**   In PJ_container_get() at /home/carni/proj/simgrid-martin/src/instr/instr_paje_containers.cpp:146
**   In TRACE_msg_process_suspend() at /home/carni/proj/simgrid-martin/src/msg/instr_msg_process.cpp:90
**   In MSG_process_suspend() at /home/carni/proj/simgrid-martin/src/msg/msg_process.cpp:441
**   In slave() at /home/carni/proj/simgrid-martin/examples/msg/masterslave/masterslave_kill.c:20
**   In _ZN7simgrid5simix10RawContext7wrapperEPv() at /home/carni/proj/simgrid-martin/src/simix/RawContext.cpp:325
Abandon (core dumped)
```

**Comment by mpoquet** [comment]
I updated my fork, reverted the changes I did and inspected what happen.
I found the same problems as before and fixed them in the same way.

I launched the tests and they seem to pass as in commit mquinson/simgrid@b7630a95, so I hope those commits did not break anything. It seems that in [the travis log you gave before](https://travis-ci.org/mquinson/simgrid/builds/70967183) the pid hack was not working but the assertion is not raised now... Has the pid generation logic changed since June? I did not put the assertion in the same spot, the previous crashes could be caused when process was NULL (_i.e._ when SIMIX process creation failed).

Can you confirm me the following commits solve the problem?
With them I can obtain traces of my simulator and of the masterslave_kill.c example.

### Problems and Fixes
#### Problem 1: SIMIX process creation was done before TRACE process creation
The TRACE process creation was done just after the SIMIX process creation (in MSG_process_create_with_environment).

If the SIMIX process creation starts the new process instantly, it can lead to using a non-created container during the process execution (which gives the error described in issue 15).
##### Fix 1
Invert the SIMIX and TRACE process creation.
To do so, the pid of the future SIMIX process must be hacked.
This is done in mpoquet/simgrid@d1673ac

#### Problem 2: Double destruction of a TRACE process crashed
When solving problem 1, it looks like that the process destruction is done twice, which led to program exit because the container was not found anymore.
##### Fix 2
Use PJ_container_get_or_null and test returned valud instead of using PJ_container_get.
This is done in mpoquet/simgrid@28551df

#### Problem 3: Code redundancy in TRACE_msg_process_end
The two functions did the same thing and TRACE_msg_process_end was only called once.
##### Fix 3.1
Make TRACE_msg_process_end call TRACE_msg_process_destroy.
This is done in mpoquet/simgrid@28551df
##### Fix 3.2
Remove of TRACE_msg_process_end.
This is done in mpoquet/simgrid@b771e08

### Minor change
Added a test of TRACE_msg_process_is_enabled in TRACE_msg_process_destroy (it was the only function that was not testing TRACE_msg_process_is_enabled in the file).

### Possible memory leak
It looks like the TRACE process is not destroyed when the SIMIX process couldn't be created.
I added a FIXME comment about it in MSG_process_create_with_environment.

### Non-passing tests
```
98% tests passed, 10 tests failed out of 520

Total Test time (real) =  84.15 sec

The following tests FAILED:
         64 - tesh-msg-storage-basic-thread (Failed)
         65 - tesh-msg-storage-basic-ucontext (Failed)
         66 - tesh-msg-storage-basic-raw (Failed)
         73 - msg-file (Failed)
         74 - msg-storage (Failed)
         75 - msg-remote-io (Failed)
        244 - s4u-io-thread (Failed)
        245 - s4u-io-ucontext (Failed)
        246 - s4u-io-raw (Failed)
        247 - s4u-io-boost (Failed)
```

**Comment by mquinson** [comment]
Whaou, that's a very impressive contribution. Thanks for the patch and the very detailed comments.

As I commented on the patch, it does not compile on Travis. You need to activate the "enable_compile_warnings" cmake option to compile any code that you plan to integrate. Not a big deal, I hope that you'll be able to do it soon so that I can integrate your patch.

On patch1: instead of playing cleaver (but fragile) tricks with the next-pid, what about moving the call to TRACE_msg_process_create within the process creation? That would probably be in smx_process.cpp:SIMIX_process_create() If you don't have the time to do so, I'll do it myself after integrating your code (when it compiles).

Patch2: it looks very good, thank you. I'm a bit frustrated that we did not understand the problem that you are fixing, but that's fine. The SimGrid code base is very frustrating at the moment, I'm used to it :(

The other patches seem just perfect, thank you.

The leak is not a problem. It'd be better to cleanly fail, but if SimGrid is not able anymore to create a process, its end is very close, so memleaking is not a problem.

Side note: try to keep the first line of your commit log under 60 or 80 chars, to avoid having github (and others) cutting it in the middle. But that's just a picky cosmetics...

I am very happy about these changes, thank you. 
Mt

**Comment by mquinson** [comment]
the PR is integrated, and it actually fixes the problem. Thus closing the issue.

Many thanks.
