### ISSUE TITLE
Msg.ireceive without message in the mailbox gives strange results

### ISSUE THREAD

**Issue by orion78fr** [mquinson/simgrid#37]
This bug has been observed in java, but should be present in C as well. Observed on commit b23e1eb.

Making an ireceive on a mailbox while there is no message gives strange result.

```Java
String mailbox = "my_mailbox";
Task.listen(mailbox); // returns false
Task.irecv(mailbox); // returns non-null Comm ; expected : null
Task.listen(mailbox); // returns true ; expected : false
```

All subsequent calls to listen returns true on this mailbox.
Calling Comm.waitCompletion() on the Comm object returned by Task.irecv causes a "deadlock" according to the logged message.

**Comment by mquinson** [comment]
I see no bug, here. 

- If you listen on a newly created mailbox, then it returns false as expected.
- If you call irecv, you create an asynchronous communication, and it gives you a handle to that async. this is fairly expected.
- If you call listen on it afterward, it tells that the async that you just created is waiting (damn true)
- If you wait on the async, it blocks until someone comes to deliver a message, which may lead to a deadlock if no external process exist to deliver that message. 

So, I'd say that you are observing the expected behavior. Thus closing -- feel free to reopen if you disagree.
